[package]
name = "full_text_adventure"
version = "0.1.0"
authors = ["MTaurone <arshiahf@gmail.com>"]

[dependencies]
user_input = {git = "https://github.com/arshiahf/user_input"}
text_adventure = {git = "https://github.com/arshiahf/text_adventure"}
